# Android Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "sample-app/build.gradle" }}-{{ checksum "lifecycleaware/build.gradle" }}-{{ checksum "lifecycleaware-compiler/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "sample-app/build.gradle" }}-{{ checksum "lifecycleaware/build.gradle" }}-{{ checksum "lifecycleaware-compiler/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: sample-app/build/reports
          destination: sample-app/reports
      - store_test_results:
          path: sample-app/build/test-results
      - store_artifacts:
          path: lifecycleaware/build/reports
          destination: lifecycleaware/reports
      - store_test_results:
          path: lifecycleaware/build/test-results
      - store_artifacts:
          path: lifecycleaware-compiler/build/reports
          destination: lifecycleaware-compiler/reports
      - store_test_results:
          path: lifecycleaware-compiler/build/test-results